[package]
name = "nopo-passes"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nopo-diagnostics = { path = "../nopo-diagnostics" }
nopo-parser = { path = "../nopo-parser" }
la-arena = "0.3.0"
smol_str = "0.2.0"
thiserror = "1.0.38"
