[package]
name = "nopo-diagnostics"
version = "0.1.0"
edition = "2021"

[dependencies]
ariadne = { version = "0.3.0", features = ["auto-color"] }
nopo-diagnostics-derive = { path = "../nopo-diagnostics-derive" }
