[package]
name = "nopo-vm"
version = "0.1.0"
edition = "2021"

[dependencies]
bumpalo = "3.13.0"
la-arena = "0.3.0"
nopo-diagnostics = { path = "../nopo-diagnostics" }
nopo-parser = { path = "../nopo-parser" }
nopo-passes = { path = "../nopo-passes" }
yansi = "0.5.1"
