[package]
name = "nopoc"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1.4", features = ["derive"] }
nopo-diagnostics = { path = "../nopo-diagnostics" }
la-arena = "0.3.0"
logos = "0.12.1"
smol_str = "0.2.0"
thiserror = "1.0.38"

[dev-dependencies]
expect-test = "1.4.0"
