[package]
name = "nopo-parser"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
la-arena = "0.3.0"
logos = "0.12.1"
nopo-diagnostics = { path = "../nopo-diagnostics" }
smol_str = "0.2.0"
